[technote]
id = "SQR-059"
series_id = "SQR"
canonical_url = "https://sqr-059.lsst.io/"
github_url = "https://github.com/lsst-sqre/sqr-059"
github_default_branch = "main"
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"
[[technote.authors]]
name = {given = "Adam J.", family = "Thornton"}
internal_id = "thorntonaj"
orcid = "https://orcid.org/0000-0001-9342-6032"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
ror = "https://ror.org/048g3cy84"
